apiVersion: v1
kind: Pod
metadata:
  name: rbd
spec:
  containers:
    - image: kubernetes/pause
      name: rbd-rw
      volumeMounts:
      - name: rbd
        mountPath: /mnt/rbd
  volumes:
    - name: rbd
      rbd:
        monitors:
        - '172.16.100.10:6789'
        - '172.16.100.11:6789'
        - '172.16.100.12:6789'
        pool: kube
        image: foo
        fsType: ext4
        readOnly: true
        user: admin
        keyring: /etc/ceph/keyring
        imageformat: "2"
        imagefeatures: "layering"

